# -*- coding: utf-8 -*-
"""라벨링.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLXsbliSI4m5R1avYTQWOZGz2zI_Y4wM
"""

# 왜곡 유형 2가지(이진분류)

import os
import time
import json
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# =========================
# OpenAI 클라이언트 설정
# =========================
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")   # .env에 OPENAI_API_KEY=... 로 저장해둔 값
)


# =========================
# 경로/파일 세팅
# =========================
INPUT_CSV = "mydata.csv"              # 원본 CSV
OUTPUT_CSV = "output.csv"            # 라벨링 결과 저장

DISTORTED_COL = "distorted"
ARTICLE_TEXT_COL = "origin_article_text"

MODEL_NAME = "gpt-4.1-mini"

# =========================
# 프롬프트 불러오기
# =========================

def load_prompt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SYSTEM_PROMPT_PATH = os.path.join(BASE_DIR, "prompts", "label_system_prompt.txt")

SYSTEM_PROMPT = load_prompt(SYSTEM_PROMPT_PATH)

# =========================
# User Prompt 생성
# =========================
def build_user_prompt(row: pd.Series) -> str:
    distorted = str(row.get(DISTORTED_COL, "")).strip()
    origin_article_text = str(row.get(ARTICLE_TEXT_COL, "")).strip()

    prompt = f"""
[Distorted statement]
{distorted}

[News article text]
{origin_article_text}

위 두 텍스트를 비교해서, 시스템 메시지의 기준에 따라
"왜곡 없음(0)" / "왜곡 있음(1)" 중 하나를 선택하시오.
반드시 의미 왜곡이 뚜렷하고 해석이 달라질 때만 1을 부여하고,
애매하면 모두 0으로 분류하십시오.
"""
    return prompt



# =========================
# GPT 호출 함수
# =========================
def call_gpt_labeler(user_prompt: str, max_retries: int = 3, sleep_base: float = 2.0):
    """
    GPT 호출 + JSON 파싱 + 간단한 재시도 로직.
    """
    for attempt in range(1, max_retries + 1):
        try:
            response = client.chat.completions.create(
                model=MODEL_NAME,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.2,
            )
            content = response.choices[0].message.content
            data = json.loads(content)
            return data

        except Exception as e:
            print(f"[WARN] GPT 호출 실패 (시도 {attempt}/{max_retries}): {e}")
            if attempt == max_retries:
                print("[ERROR] 재시도 한계 도달, 이 행은 NULL로 둠.")
                return None
            time.sleep(sleep_base * attempt)


def main():
    df = pd.read_csv(INPUT_CSV)

    # 이미 컬럼이 있으면 덮어쓰지 않고 스킵할 수도 있음 (여기서는 덮어쓰기)
    if "distortion_label" not in df.columns:
        df["distortion_label"] = None
    if "distortion_rationale_ko" not in df.columns:
        df["distortion_rationale_ko"] = None

    for idx in tqdm(range(len(df)), desc="Labeling with GPT-mini"):
        # 이미 라벨 있으면 스킵 (중단 후 재시작 대비)
        if pd.notna(df.loc[idx, "distortion_label"]):
            continue

        row = df.loc[idx]
        user_prompt = build_user_prompt(row)
        result = call_gpt_labeler(user_prompt)

        if result is None:
            continue

        label = result.get("label")
        rationale_ko = result.get("rationale_ko")

        df.at[idx, "distortion_label"] = label
        df.at[idx, "distortion_rationale_ko"] = rationale_ko

        # 50개마다 중간 저장
        if idx % 50 == 0:
            df.to_csv(OUTPUT_CSV, index=False)

    df.to_csv(OUTPUT_CSV, index=False)
    print(f"완료. 결과 저장: {OUTPUT_CSV}")


if __name__ == "__main__":
    main()

# label=1 생성
import os
import time
import json
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# =========================
# OpenAI 클라이언트 설정
# =========================
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")   # .env에 OPENAI_API_KEY=... 로 저장해둔 값
)

INPUT_CSV = "mydata.csv"     # 네 CSV 경로
OUTPUT_CSV = "outdata.csv"   # 결과 저장 경로
MODEL_NAME = "gpt-4.1-mini"

# =========================
# 라벨1용 왜곡 생성 SYSTEM PROMPT
# =========================
def load_prompt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GEN_SYSTEM_PROMPT_PATH = os.path.join(BASE_DIR, "prompts", "label1_generation_prompt.txt")

GEN_SYSTEM_PROMPT = load_prompt(GEN_SYSTEM_PROMPT_PATH)


# =========================
# 생성용 user prompt
# =========================
def build_gen_prompt(row: pd.Series) -> str:
    # 기사 전체 맥락: origin_article_text 사용
    article_span = str(row.get("origin_article_text", "")).strip()
    # 기존 인용문 번역본: distorted 사용 (없으면 빈 문자열)
    base_statement = str(row.get("distorted", "")).strip()

    prompt = f"""
[News article text]
{article_span}

[Base statement]
{base_statement}

위 기사 내용을 바탕으로, 위 Distortion Criteria에서 반드시 라벨 1(왜곡 있음)으로
분류될 정도로 의미가 달라진 영어 인용문(한 문장 내지 짧은 문단)을 하나 만들어라.
"""
    return prompt

# =========================
# GPT 호출 (생성용)
# =========================
def call_gpt_generator(user_prompt: str, max_retries: int = 3, sleep_base: float = 2.0):
    for attempt in range(1, max_retries + 1):
        try:
            resp = client.chat.completions.create(
                model=MODEL_NAME,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": GEN_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.7,
            )
            content = resp.choices[0].message.content
            data = json.loads(content)
            return data

        except Exception as e:
            print(f"[WARN] GEN 호출 실패 (시도 {attempt}/{max_retries}): {e}")
            if attempt == max_retries:
                print("[ERROR] 재시도 한계 도달, 이 행은 NULL로 둠.")
                return None
            time.sleep(sleep_base * attempt)

# =========================
# 메인: CSV 전체 행에 대해 생성
# =========================
def main_generate():
    df = pd.read_csv(INPUT_CSV)

    # 새로운 왜곡문 저장할 컬럼 (없으면 생성)
    if "distorted_label1_candidate" not in df.columns:
        df["distorted_label1_candidate"] = None

    try:
        for idx in tqdm(range(len(df)), desc="Generating label-1 candidates (ALL rows)"):
            # 이미 생성된 게 있으면 스킵 (중단 후 재시작 대비)
            if pd.notna(df.loc[idx, "distorted_label1_candidate"]):
                continue

            row = df.loc[idx]
            user_prompt = build_gen_prompt(row)
            result = call_gpt_generator(user_prompt)

            if result is None:
                continue

            distorted_new = result.get("distorted", "").strip()
            if not distorted_new:
                continue

            df.at[idx, "distorted_label1_candidate"] = distorted_new

            # 선택: 50행마다 중간 저장
            if idx % 50 == 0:
                df.to_csv(OUTPUT_CSV, index=False)

    finally:
        df.to_csv(OUTPUT_CSV, index=False)
        print(f"[INFO] 생성 결과 저장 완료 (총 {len(df)} rows): {OUTPUT_CSV}")


if __name__ == "__main__":
    main_generate()